HUB = "hub"
DOMAIN = "crestron"
CONF_PORT = "port"
CONF_TO_HUB = "to_joins"
CONF_FROM_HUB = "from_joins"
CONF_JOIN = "join"
CONF_SCRIPT = "script"
CONF_IS_ON_JOIN = "is_on_join"
# Climate (simplified AC: power + single setpoint + fan speed + current temp).
CONF_SET_TEMP_JOIN = "set_temp_join"
CONF_REG_TEMP_JOIN = "reg_temp_join"
CONF_MODE_COOL_JOIN = "mode_cool_join"
CONF_MODE_HEAT_JOIN = "mode_heat_join"
CONF_MODE_FAN_JOIN = "mode_fan_join"
CONF_MODE_DRY_JOIN = "mode_dry_join"
CONF_FAN_LOW_JOIN = "fan_low_join"
CONF_FAN_MED_JOIN = "fan_med_join"
CONF_FAN_HIGH_JOIN = "fan_high_join"
CONF_FAN_AUTO_JOIN = "fan_auto_join"
CONF_IS_OPENING_JOIN = "is_opening_join"
CONF_IS_CLOSING_JOIN = "is_closing_join"
CONF_IS_CLOSED_JOIN = "is_closed_join"
CONF_OPEN_JOIN = "open_join"
CONF_CLOSE_JOIN = "close_join"
CONF_STOP_JOIN = "stop_join"
CONF_POS_JOIN = "pos_join"
CONF_BRIGHTNESS_JOIN = "brightness_join"
CONF_COLOR_TEMP_JOIN = "color_temp_join"
CONF_MUTE_JOIN = "mute_join"
CONF_VOLUME_JOIN = "volume_join"
CONF_SOURCE_NUM_JOIN = "source_number_join"
CONF_SOURCES = "sources"
CONF_VALUE_JOIN = "value_join"
CONF_DIVISOR = "divisor"
CONF_SWITCH_JOIN = "switch_join"
CONF_ON_JOIN = "on_join"
CONF_OFF_JOIN = "off_join"
CONF_STATE_JOIN = "state_join"
# Multi-state feedback: {label: digital_join}. Used by switch (on if any
# active, exposes active label as a "mode" attribute) and sensor (text value).
CONF_MODE_JOINS = "mode_joins"
# select platform: {option_label: digital_join}
CONF_OPTIONS = "options"
# number platform bounds
CONF_MIN = "min"
CONF_MAX = "max"
CONF_STEP = "step"
# Device grouping: entities sharing device_id show under one HA device.
CONF_DEVICE_ID = "device_id"
CONF_DEVICE_NAME = "device_name"
